apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: stock-portfolio-namespace
data:
  nginx.conf: |
   events {}

    http {
      server {
        listen 80;

        location /stocks/ {
          proxy_pass https://stocks-service:6000;
        }

        location /capital-gains/ {
          proxy_pass https://capital-gains-service:6001;
        }
      }
    }