apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: stock-portfolio-namespace
data:
  nginx.conf: |
   events {}

    http {
      server {
       listen 80;
    
       location / {   
          proxy_pass http://stocks-service:6000/;
        }
       
    
       location /stocks {
          rewrite ^/stocks(.*)$ /stocks$1 break;   
          proxy_pass http://stocks-service:6000;
        }

       location /capital-gains {
          rewrite ^/capital-gains(.*)$ /capital-gains$1 break;
          proxy_pass http://capital-gains-service:6001;
        }
      }
    }