apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: stock-portfolio-namespace
spec:
  selector:
    app: capital-gains-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
