apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: stock-portfolio-namespace
spec:
  selector:
    app: stocks-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 8000
