apiVersion: apps/v1
kind: Deployment
metadata:
  name: capital-gains-app
  namespace: stock-portfolio-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capital-gains-app
  template:
    metadata:
      labels:
        app: capital-gains-app
    spec:
      containers:
        - name: capital-gains-app
          image: capital-gains-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
