apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: stock-portfolio-namespace
spec:
  selector:
    app: capital-gains-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 8080
