apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
  namespace: stock-portfolio-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi