apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
  namespace: my-namespace # TODO: update to the real name space
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data  # Path on the Node's filesystem