apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: stock-portfolio-namespace
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
