apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: stock-portfolio-namespace
spec:
  selector:
    app: database
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
      nodePort: 27017
